# These settings override default autograde settings for the course
general:
  display_name: 'Video game monsters, part 6' # Mandatory
  handin_filename: 'Monsters6.zip' # Mandatory
  handin_contents: ['Monster.java', 'GameUtils.java']
