# These settings override default autograde settings for the course
general:
  display_name: 'DTU Christmas party' # Mandatory
  handin_filename: 'Party.zip' # Mandatory
  handin_contents: ['Person.java', 'FileUtils.java']
